services:
  frontend:
    container_name: frontend
    build:
      context: '.'
      dockerfile: './frontend/Dockerfile'
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"
    # command: sh -c "yarn install && yarn dev" # yarnだとうまくいかない
    ports:
      - "3000:3000"
    networks:
      - myportfolio

  backend:
    container_name: backend
    build:
      context: '.'
      dockerfile: './backend/Dockerfile'
    volumes:
      - ./backend:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev && npx prisma generate"  # 最後のはPrismaクライアントを生成
    ports:
      - "4000:4000"
    networks:
      - myportfolio

  prisma-studio:
    container_name: prisma-studio
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npx prisma studio"
    ports:
      - "5555:5555"
    networks:
      - myportfolio

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myportfolio
      MYSQL_USER: local
      MYSQL_PASSWORD: password
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3306:3306"
    networks:
      - myportfolio

networks:
  myportfolio:
    external: true