services:
  node:
    build:
      context: .
    tty: true
    volumes:
      - ./:/app
    environment:
      - WATCHPACK_POLLING=true
    # コンテナ立ち上げの際に実行するコマンド（ローカルサーバー起動）
    # command: sh -c " run dev"
    ports:
      - "3000:3000"
